services:
  db:
    image: postgres:15.4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_NAME}

  django:
    build: ./django
    command: uvicorn config.asgi:application --host  0.0.0.0 --port 8000
    volumes:
      - ./django:/code/
      - static_django:/code/staticfiles/
    expose:
      - 8000
    depends_on:
      - db
    
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - static_django:/code/staticfiles/
      - ./react/build/:/code/build/
    depends_on:
      - django
  
  

volumes:
  postgres-data: #db_dataを作成
  static_django: #静的データをdjango <-> nginxで共有