services:
  db:
    image: postgres:15.4
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  django:
    build: ./django
    command: uvicorn config.asgi:application --host  0.0.0.0 --port 8000
    volumes:
      - ./django:/code/
      - static_django:/code/staticfiles/
    expose:
      - 8000
    depends_on:
      - db
  
  react:
    build: ./react
    volumes:
     - ./react/build/:/code/build/
     - static_react:/code/build/
    
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - static_django:/code/staticfiles/
      - static_react:/code/build/
    depends_on:
      - django
      - react

volumes:
  postgres-data: #db_dataを作成
  static_django: #静的データをdjango <-> nginxで共有
  static_react: